name: midas_wallet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets :
  - images/

  fonts:
    - family: Jakarta
      fonts:
       - asset: fonts/PlusJakartaSansRegular.ttf
       - asset: fonts/PlusJakartaSansBold.ttf
         weight: 700
       - asset: fonts/PlusJakartaSansExtraBold.ttf
         weight: 800
       - asset: fonts/PlusJakartaSansSemiBold.ttf
         weight: 600
       - asset: fonts/PlusJakartaSansSemiItalic.ttf
         style: italic

